### ISSUE TITLE
Showing excerpt generated by WordPress instead of the whole passage in the index page

### ISSUE THREAD

**Issue by earthjasonlin** [andersnoren/lovecraft#1]
I'm using your Lovecraft theme for WordPress and it's really amazing and attractive. However, I noticed that it displays the whole passage on the index page. It is sometimes too long that it takes some time to navigate to the next passage and is not friendly for statistics analyzer, either.

So, is there a way to show only excerpt generated by WordPress instead of the whole passage in the index page?

**Comment by andersnoren** [comment]
@earthjasonlin I'm glad you like it! You can't change it to an excerpt everywhere automatically, but you can use the "More Link" block in the block editor to insert at "Read More" button like on the demo site: https://andersnoren.se/themes/lovecraft/
